table top_wards_complaints
	lineageTag: 5ef82561-344a-4a96-87b9-433c36c2d17e

	column ward_id
		dataType: int64
		formatString: 0
		lineageTag: fbfec8d5-669c-4945-9fe8-2c079f57fa13
		summarizeBy: sum
		sourceColumn: ward_id

		annotation SummarizationSetBy = Automatic

	column 'Ward Title'
		dataType: string
		lineageTag: aa54b23a-bd17-4cc3-89d3-ea317bd42373
		summarizeBy: none
		sourceColumn: Ward Title

		annotation SummarizationSetBy = Automatic

	column 'Number of Complaints'
		dataType: int64
		formatString: 0
		lineageTag: 884e94e8-2931-4a38-afdd-cd3203b5c1ef
		summarizeBy: sum
		sourceColumn: Number of Complaints

		annotation SummarizationSetBy = Automatic

	partition top_wards_complaints = m
		mode: import
		source =
				let
				  Source = Csv.Document(File.Contents("C:\Users\anant\OneDrive\Desktop\Assignment 1\top_wards_complaints.csv"), [Delimiter = ",", Columns = 3, QuoteStyle = QuoteStyle.None]),
				  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"ward_id", Int64.Type}, {"ward_title", type text}, {"number_of_complaints", Int64.Type}}, "en-US"),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed column type",{{"ward_title", "Ward Title"}, {"number_of_complaints", "Number of Complaints"}})
				in
				  #"Renamed Columns"

